In [25]:
#import python libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [26]:
#import data
df = pd.read_csv('CarPrice_Assignment.csv')

In [27]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [28]:
import re
from difflib import SequenceMatcher
import pandas as pd

def normalize_name(value):
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()

car_names = df["CarName"].dropna().astype(str)
unique_names = car_names.unique()

# Print every distinct CarName with its position in the unique list.
for index, name in enumerate(unique_names, start=1):
    print(f"{index:3}. {name}")

# Find likely brand/model spelling variants.
comparison_rows = []

for i, name_i in enumerate(unique_names):
    normalized_i = normalize_name(name_i)

    for j in range(i + 1, len(unique_names)):
        name_j = unique_names[j]
        normalized_j = normalize_name(name_j)

        if normalized_i == normalized_j:
            continue

        similarity = SequenceMatcher(None, normalized_i, normalized_j).ratio()

        # A high score indicates very similar spelling.
        if similarity >= 0.82:
            comparison_rows.append({
                "car_name_1": name_i,
                "car_name_2": name_j,
                "similarity": round(similarity * 100, 2)
            })

pd.DataFrame(comparison_rows).sort_values(
    "similarity",
    ascending=False
).to_string(index=False)

  1. alfa-romero giulia
  2. alfa-romero stelvio
  3. alfa-romero Quadrifoglio
  4. audi 100 ls
  5. audi 100ls
  6. audi fox
  7. audi 5000
  8. audi 4000
  9. audi 5000s (diesel)
 10. bmw 320i
 11. bmw x1
 12. bmw x3
 13. bmw z4
 14. bmw x4
 15. bmw x5
 16. chevrolet impala
 17. chevrolet monte carlo
 18. chevrolet vega 2300
 19. dodge rampage
 20. dodge challenger se
 21. dodge d200
 22. dodge monaco (sw)
 23. dodge colt hardtop
 24. dodge colt (sw)
 25. dodge coronet custom
 26. dodge dart custom
 27. dodge coronet custom (sw)
 28. honda civic
 29. honda civic cvcc
 30. honda accord cvcc
 31. honda accord lx
 32. honda civic 1500 gl
 33. honda accord
 34. honda civic 1300
 35. honda prelude
 36. honda civic (auto)
 37. isuzu MU-X
 38. isuzu D-Max
 39. isuzu D-Max V-Cross
 40. jaguar xj
 41. jaguar xf
 42. jaguar xk
 43. maxda rx3
 44. maxda glc deluxe
 45. mazda rx2 coupe
 46. mazda rx-4
 47. mazda glc deluxe
 48. mazda 626
 49. mazda glc
 50. mazda rx-7 gs
 51. mazda glc 4
 52. mazda glc custom l
 53. mazda glc custom
 54. buick electra 225 custom
 55. buick century luxus (sw)
 56. buick century
 57. buick skyhawk
 58. buick opel isuzu deluxe
 59. buick skylark
 60. buick century special
 61. buick regal sport coupe (turbo)
 62. mercury cougar
 63. mitsubishi mirage
 64. mitsubishi lancer
 65. mitsubishi outlander
 66. mitsubishi g4
 67. mitsubishi mirage g4
 68. mitsubishi montero
 69. mitsubishi pajero
 70. Nissan versa
 71. nissan gt-r
 72. nissan rogue
 73. nissan latio
 74. nissan titan
 75. nissan leaf
 76. nissan juke
 77. nissan note
 78. nissan clipper
 79. nissan nv200
 80. nissan dayz
 81. nissan fuga
 82. nissan otti
 83. nissan teana
 84. nissan kicks
 85. peugeot 504
 86. peugeot 304
 87. peugeot 504 (sw)
 88. peugeot 604sl
 89. peugeot 505s turbo diesel
 90. plymouth fury iii
 91. plymouth cricket
 92. plymouth satellite custom (sw)
 93. plymouth fury gran sedan
 94. plymouth valiant
 95. plymouth duster
 96. porsche macan
 97. porcshce panamera
 98. porsche cayenne
 99. porsche boxter
100. renault 12tl
101. renault 5 gtl
102. saab 99e
103. saab 99le
104. saab 99gle
105. subaru
106. subaru dl
107. subaru brz
108. subaru baja
109. subaru r1
110. subaru r2
111. subaru trezia
112. subaru tribeca
113. toyota corona mark ii
114. toyota corona
115. toyota corolla 1200
116. toyota corona hardtop
117. toyota corolla 1600 (sw)
118. toyota carina
119. toyota mark ii
120. toyota corolla
121. toyota corolla liftback
122. toyota celica gt liftback
123. toyota corolla tercel
124. toyota corona liftback
125. toyota starlet
126. toyota tercel
127. toyota cressida
128. toyota celica gt
129. toyouta tercel
130. vokswagen rabbit
131. volkswagen 1131 deluxe sedan
132. volkswagen model 111
133. volkswagen type 3
134. volkswagen 411 (sw)
135. volkswagen super beetle
136. volkswagen dasher
137. vw dasher
138. vw rabbit
139. volkswagen rabbit
140. volkswagen rabbit custom
141. volvo 145e (sw)
142. volvo 144ea
143. volvo 244dl
144. volvo 245
145. volvo 264gl
146. volvo diesel
147. volvo 246

'             car_name_1                car_name_2  similarity\n       vokswagen rabbit         volkswagen rabbit       96.97\n          toyota tercel            toyouta tercel       96.30\n            audi 100 ls                audi 100ls       95.24\n              saab 99le                saab 99gle       94.74\n               saab 99e                 saab 99le       94.12\n     mazda glc custom l          mazda glc custom       94.12\n       maxda glc deluxe          mazda glc deluxe       93.75\ntoyota corolla liftback    toyota corona liftback       93.33\n   dodge coronet custom dodge coronet custom (sw)       93.02\n      mitsubishi mirage      mitsubishi mirage g4       91.89\n            peugeot 504               peugeot 304       90.91\n              mazda glc               mazda glc 4       90.00\n          toyota corona            toyota corolla       88.89\n              subaru r1                 subaru r2       88.89\n               saab 99e                saab 99gle       88.89\n              audi 5000                 audi 4000       88.89\n              volvo 245                 volvo 246       88.89\n              jaguar xf                 jaguar xk       88.89\n        honda accord lx              honda accord       88.89\n              jaguar xj                 jaguar xf       88.89\n              jaguar xj                 jaguar xk       88.89\n            peugeot 504          peugeot 504 (sw)       88.00\n    toyota corolla 1200  toyota corolla 1600 (sw)       87.80\n      mitsubishi lancer      mitsubishi outlander       86.49\n    honda civic 1500 gl          honda civic 1300       85.71\n    toyota corolla 1200            toyota corolla       84.85\n          buick skyhawk             buick skylark       84.62\n          toyota corona             toyota carina       84.62\n             subaru brz                 subaru r1       84.21\n             subaru brz                 subaru r2       84.21\n           nissan titan              nissan teana       83.33\n                 bmw x3                    bmw x4       83.33\n                 bmw x1                    bmw x3       83.33\n                 bmw x1                    bmw x4       83.33\n                 bmw x1                    bmw x5       83.33\n                 bmw x3                    bmw x5       83.33\n                 bmw x4                    bmw x5       83.33\n            peugeot 304             peugeot 604sl       83.33\n            peugeot 504             peugeot 604sl       83.33\n                 bmw z4                    bmw x4       83.33\n      volkswagen rabbit  volkswagen rabbit custom       82.93\n      honda accord cvcc              honda accord       82.76\n      mitsubishi lancer         mitsubishi pajero       82.35'

In [29]:
matches = pd.DataFrame(comparison_rows)

if matches.empty:
    print("No name pairs met the 82% similarity threshold.")
else:
    display(matches.sort_values("similarity", ascending=False))

                 car_name_1                 car_name_2  similarity
40         vokswagen rabbit          volkswagen rabbit       96.97
39            toyota tercel             toyouta tercel       96.30
0               audi 100 ls                 audi 100ls       95.24
30                saab 99le                 saab 99gle       94.74
28                 saab 99e                  saab 99le       94.12
18       mazda glc custom l           mazda glc custom       94.12
16         maxda glc deluxe           mazda glc deluxe       93.75
38  toyota corolla liftback     toyota corona liftback       93.33
9      dodge coronet custom  dodge coronet custom (sw)       93.02
20        mitsubishi mirage       mitsubishi mirage g4       91.89
24              peugeot 504                peugeot 304       90.91
17                mazda glc                mazda glc 4       90.00
35            toyota corona             toyota corolla       88.89
33                subaru r1                  subaru r2       88.89
29                 saab 99e                 saab 99gle       88.89
1                 audi 5000                  audi 4000       88.89
42                volvo 245                  volvo 246       88.89
15                jaguar xf                  jaguar xk       88.89
11          honda accord lx               honda accord       88.89
13                jaguar xj                  jaguar xf       88.89
14                jaguar xj                  jaguar xk       88.89
25              peugeot 504           peugeot 504 (sw)       88.00
36      toyota corolla 1200   toyota corolla 1600 (sw)       87.80
21        mitsubishi lancer       mitsubishi outlander       86.49
12      honda civic 1500 gl           honda civic 1300       85.71
37      toyota corolla 1200             toyota corolla       84.85
19            buick skyhawk              buick skylark       84.62
34            toyota corona              toyota carina       84.62
31               subaru brz                  subaru r1       84.21
32               subaru brz                  subaru r2       84.21
23             nissan titan               nissan teana       83.33
5                    bmw x3                     bmw x4       83.33
2                    bmw x1                     bmw x3       83.33
3                    bmw x1                     bmw x4       83.33
4                    bmw x1                     bmw x5       83.33
6                    bmw x3                     bmw x5       83.33
8                    bmw x4                     bmw x5       83.33
27              peugeot 304              peugeot 604sl       83.33
26              peugeot 504              peugeot 604sl       83.33
7                    bmw z4                     bmw x4       83.33
41        volkswagen rabbit   volkswagen rabbit custom       82.93
10        honda accord cvcc               honda accord       82.76
22        mitsubishi lancer          mitsubishi pajero       82.35

In [30]:
df["CarName"].nunique()

147

In [31]:
df["CarName"].nunique

<bound method IndexOpsMixin.nunique of 0            alfa-romero giulia
1           alfa-romero stelvio
2      alfa-romero Quadrifoglio
3                   audi 100 ls
4                    audi 100ls
                 ...
200             volvo 145e (sw)
201                 volvo 144ea
202                 volvo 244dl
203                   volvo 246
204                 volvo 264gl
Name: CarName, Length: 205, dtype: object>

In [32]:
# Map common brand misspellings to the correct brand names.
brand_corrections = {
    "alfa-romero": "alfa romeo",
    "chevrollet": "chevrolet",
    "maxda": "mazda",
    "porcshce": "porsche",
    "toyouta": "toyota",
    "vokswagen": "volkswagen",
    "vw": "volkswagen",
}

# Normalise the dictionary keys so they match the output
# of normalize_name().
brand_corrections = {
    normalize_name(key): value
    for key, value in brand_corrections.items()
}

def correct_brand(value):
    if pd.isna(value):
        return value

    parts = str(value).split(maxsplit=1)

    # The first whitespace-separated token is the brand.
    brand = normalize_name(parts[0])
    corrected_brand = brand_corrections.get(brand, parts[0])

    # Preserve the model name for now.
    if len(parts) > 1:
        return f"{corrected_brand} {parts[1]}"

    return corrected_brand

df["CarName"] = df["CarName"].apply(correct_brand)

In [33]:
print(df["CarName"].unique().tolist())

['alfa romeo giulia', 'alfa romeo stelvio', 'alfa romeo Quadrifoglio', 'audi 100 ls', 'audi 100ls', 'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)', 'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5', 'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300', 'dodge rampage', 'dodge challenger se', 'dodge d200', 'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)', 'dodge coronet custom', 'dodge dart custom', 'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc', 'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl', 'honda accord', 'honda civic 1300', 'honda prelude', 'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ', 'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk', 'mazda rx3', 'mazda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4', 'mazda 626', 'mazda glc', 'mazda rx-7 gs', 'mazda glc 4', 'mazda glc custom l', 'mazda glc custom', 'buick electra 225 custom', 'buick century luxus (sw)', 'buick century', 'buick skyhawk', 'buick opel isuzu deluxe', 'buick skylark', 'buick century special', 'buick regal sport coupe (turbo)', 'mercury cougar', 'mitsubishi mirage', 'mitsubishi lancer', 'mitsubishi outlander', 'mitsubishi g4', 'mitsubishi mirage g4', 'mitsubishi montero', 'mitsubishi pajero', 'Nissan versa', 'nissan gt-r', 'nissan rogue', 'nissan latio', 'nissan titan', 'nissan leaf', 'nissan juke', 'nissan note', 'nissan clipper', 'nissan nv200', 'nissan dayz', 'nissan fuga', 'nissan otti', 'nissan teana', 'nissan kicks', 'peugeot 504', 'peugeot 304', 'peugeot 504 (sw)', 'peugeot 604sl', 'peugeot 505s turbo diesel', 'plymouth fury iii', 'plymouth cricket', 'plymouth satellite custom (sw)', 'plymouth fury gran sedan', 'plymouth valiant', 'plymouth duster', 'porsche macan', 'porsche panamera', 'porsche cayenne', 'porsche boxter', 'renault 12tl', 'renault 5 gtl', 'saab 99e', 'saab 99le', 'saab 99gle', 'subaru', 'subaru dl', 'subaru brz', 'subaru baja', 'subaru r1', 'subaru r2', 'subaru trezia', 'subaru tribeca', 'toyota corona mark ii', 'toyota corona', 'toyota corolla 1200', 'toyota corona hardtop', 'toyota corolla 1600 (sw)', 'toyota carina', 'toyota mark ii', 'toyota corolla', 'toyota corolla liftback', 'toyota celica gt liftback', 'toyota corolla tercel', 'toyota corona liftback', 'toyota starlet', 'toyota tercel', 'toyota cressida', 'toyota celica gt', 'volkswagen rabbit', 'volkswagen 1131 deluxe sedan', 'volkswagen model 111', 'volkswagen type 3', 'volkswagen 411 (sw)', 'volkswagen super beetle', 'volkswagen dasher', 'volkswagen rabbit custom', 'volvo 145e (sw)', 'volvo 144ea', 'volvo 244dl', 'volvo 245', 'volvo 264gl', 'volvo diesel', 'volvo 246']

In [34]:
pd.DataFrame(
    sorted(df["CarName"].dropna().unique()),
    columns=["CarName"]
)

                     CarName
0               Nissan versa
1    alfa romeo Quadrifoglio
2          alfa romeo giulia
3         alfa romeo stelvio
4                audi 100 ls
..                       ...
137              volvo 244dl
138                volvo 245
139                volvo 246
140              volvo 264gl
141             volvo diesel

[142 rows x 1 columns]

In [35]:
corrections = pd.read_excel("Car_Name_Corrections.xlsx")

def normalize_name(value):
    value = str(value).strip().lower()
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()

# Create a dictionary containing ALL proposed standardisations
# all_model_corrections = {
#     normalize_name(row["Original Input Name"]):
#         row["Standardized Name"]
#     for _, row in corrections.iterrows()
# }

all_model_corrections = {
    normalize_name(row["Original Input Name"]):
        row["Standardized Name"]
    for _, row in corrections.iterrows()
}

# Create a more conservative dictionary containing only
# spelling fixes and typo corrections
typo_corrections = corrections[
    corrections["Action / Correction Category"]
    .str.strip()
    .eq("Typo / Spelling Fix")
]
model_corrections = {
    row["Original Input Name"]: row["Standardized Name"]
    for _, row in typo_corrections.iterrows()
}


print("All proposed mappings:", len(all_model_corrections))
print("Typo-only mappings:", len(model_corrections))

All proposed mappings: 142
Typo-only mappings: 7

In [36]:
print(corrections)

         Original Input Name        Make               Standardized Name  \
0          alfa romeo giulia  Alfa Romeo               alfa romeo giulia
1         alfa romeo stelvio  Alfa Romeo              alfa romeo stelvio
2    alfa romeo Quadrifoglio  Alfa Romeo  alfa romeo giulia quadrifoglio
3                audi 100 ls        Audi                        audi 100
4                 audi 100ls        Audi                        audi 100
..                       ...         ...                             ...
137              volvo 244dl       Volvo                volvo 240 series
138                volvo 245       Volvo                volvo 240 series
139              volvo 264gl       Volvo                volvo 260 series
140             volvo diesel       Volvo                volvo 240 diesel
141                volvo 246       Volvo                volvo 240 series

    Action / Correction Category  \
0               Valid Model Name
1               Valid Model Name
2           Incomplete / Missing
3           Trim / Engine Suffix
4            Typo / Spelling Fix
..                           ...
137         Trim / Engine Suffix
138             Valid Model Name
139         Trim / Engine Suffix
140         Incomplete / Missing
141             Valid Model Name

    Automotive Details & Expert Context (Engine, Power, Dimensions)
0    Compact executive sedan. 2.0L Turbo I4 (~280 h...
1    Mid-size luxury performance SUV sharing Giorgi...
2    Quadrifoglio ('4-leaf clover') is Alfa's perfo...
3    1.8L 4-cyl (~100 hp) C1 executive sedan. 'LS' ...
4    Missing space before trim suffix. Exactly iden...
..                                                 ...
137  '244' = 200-Series 4-Door Sedan. 'dl' = De Lux...
138           '245' = 200-Series 5-Door Station Wagon.
139  '264' = 200-Series, 6-Cyl (PRV V6 engine), 4-D...
140  Incomplete model string referring to 240/740 d...
141  Rare factory code for 200-series equipped with...

[142 rows x 5 columns]

In [37]:
print(typo_corrections)

   Original Input Name     Make Standardized Name  \
4           audi 100ls     Audi          audi 100
44          isuzu MU-X    Isuzu        isuzu mu-x
45        isuzu D-Max     Isuzu       isuzu d-max
50           mazda rx3    Mazda        mazda rx-3
52     mazda rx2 coupe    Mazda        mazda rx-2
68        Nissan versa   Nissan      nissan versa
97      porsche boxter  Porsche   porsche boxster

   Action / Correction Category  \
4           Typo / Spelling Fix
44          Typo / Spelling Fix
45          Typo / Spelling Fix
50          Typo / Spelling Fix
52          Typo / Spelling Fix
68          Typo / Spelling Fix
97          Typo / Spelling Fix

   Automotive Details & Expert Context (Engine, Power, Dimensions)
4   Missing space before trim suffix. Exactly iden...
44  Capitalization fix. Mid-size body-on-frame 7-s...
45  Trailing space fix & capitalization standardiz...
50  Hyphenation standardization (`rx-3`). Lightwei...
52  Hyphenation (`rx-2`) & strip 'coupe' body styl...
68  Capitalization fix ('Nissan' -> 'nissan'). Sub...
97  Spelling fix: Missing 's' -> Boxster (portmant...

In [38]:
type(typo_corrections)

pandas.core.frame.DataFrame

In [39]:
model_corrections

{'audi 100ls': 'audi 100',
 'isuzu MU-X': 'isuzu mu-x',
 'isuzu D-Max ': 'isuzu d-max',
 'mazda rx3': 'mazda rx-3',
 'mazda rx2 coupe': 'mazda rx-2',
 'Nissan versa': 'nissan versa',
 'porsche boxter': 'porsche boxster'}

In [40]:

model_corrections["audi 100ls"] = "audi 100 ls"

df["CarName"] = (
    df["CarName"]
    .replace(model_corrections)
)

# Check the corrected values
print(df["CarName"].value_counts().sort_index())

CarName
alfa romeo Quadrifoglio    1
alfa romeo giulia          1
alfa romeo stelvio         1
audi 100 ls                3
audi 4000                  1
                          ..
volvo 244dl                2
volvo 245                  1
volvo 246                  1
volvo 264gl                2
volvo diesel               1
Name: count, Length: 141, dtype: int64

In [41]:
all_model_corrections

{'alfa romeo giulia': 'alfa romeo giulia',
 'alfa romeo stelvio': 'alfa romeo stelvio',
 'alfa romeo quadrifoglio': 'alfa romeo giulia quadrifoglio',
 'audi 100 ls': 'audi 100',
 'audi 100ls': 'audi 100',
 'audi fox': 'audi fox',
 'audi 5000': 'audi 5000',
 'audi 4000': 'audi 4000',
 'audi 5000s diesel': 'audi 5000',
 'bmw 320i': 'bmw 320i',
 'bmw x1': 'bmw x1',
 'bmw x3': 'bmw x3',
 'bmw z4': 'bmw z4',
 'bmw x4': 'bmw x4',
 'bmw x5': 'bmw x5',
 'buick electra 225 custom': 'buick electra',
 'buick century luxus sw': 'buick century',
 'buick century': 'buick century',
 'buick skyhawk': 'buick skyhawk',
 'buick opel isuzu deluxe': 'buick opel',
 'buick skylark': 'buick skylark',
 'buick century special': 'buick century',
 'buick regal sport coupe turbo': 'buick regal',
 'chevrolet impala': 'chevrolet impala',
 'chevrolet monte carlo': 'chevrolet monte carlo',
 'chevrolet vega 2300': 'chevrolet vega',
 'dodge rampage': 'dodge rampage',
 'dodge challenger se': 'dodge challenger',
 'dodge d200': 'dodge d200',
 'dodge monaco sw': 'dodge monaco',
 'dodge colt hardtop': 'dodge colt',
 'dodge colt sw': 'dodge colt',
 'dodge coronet custom': 'dodge coronet',
 'dodge dart custom': 'dodge dart',
 'dodge coronet custom sw': 'dodge coronet',
 'honda civic': 'honda civic',
 'honda civic cvcc': 'honda civic',
 'honda accord cvcc': 'honda accord',
 'honda accord lx': 'honda accord',
 'honda civic 1500 gl': 'honda civic',
 'honda accord': 'honda accord',
 'honda civic 1300': 'honda civic',
 'honda prelude': 'honda prelude',
 'honda civic auto': 'honda civic',
 'isuzu mu x': 'isuzu mu-x',
 'isuzu d max': 'isuzu d-max',
 'isuzu d max v cross': 'isuzu d-max',
 'jaguar xj': 'jaguar xj',
 'jaguar xf': 'jaguar xf',
 'jaguar xk': 'jaguar xk',
 'mazda rx3': 'mazda rx-3',
 'mazda glc deluxe': 'mazda glc',
 'mazda rx2 coupe': 'mazda rx-2',
 'mazda rx 4': 'mazda rx-4',
 'mazda 626': 'mazda 626',
 'mazda glc': 'mazda glc',
 'mazda rx 7 gs': 'mazda rx-7',
 'mazda glc 4': 'mazda glc',
 'mazda glc custom l': 'mazda glc',
 'mazda glc custom': 'mazda glc',
 'mercury cougar': 'mercury cougar',
 'mitsubishi mirage': 'mitsubishi mirage',
 'mitsubishi lancer': 'mitsubishi lancer',
 'mitsubishi outlander': 'mitsubishi outlander',
 'mitsubishi g4': 'mitsubishi mirage g4',
 'mitsubishi mirage g4': 'mitsubishi mirage g4',
 'mitsubishi montero': 'mitsubishi pajero',
 'mitsubishi pajero': 'mitsubishi pajero',
 'nissan versa': 'nissan versa',
 'nissan gt r': 'nissan gt-r',
 'nissan rogue': 'nissan rogue',
 'nissan latio': 'nissan latio',
 'nissan titan': 'nissan titan',
 'nissan leaf': 'nissan leaf',
 'nissan juke': 'nissan juke',
 'nissan note': 'nissan note',
 'nissan clipper': 'nissan clipper',
 'nissan nv200': 'nissan nv200',
 'nissan dayz': 'nissan dayz',
 'nissan fuga': 'nissan fuga',
 'nissan otti': 'nissan otti',
 'nissan teana': 'nissan teana',
 'nissan kicks': 'nissan kicks',
 'peugeot 504': 'peugeot 504',
 'peugeot 304': 'peugeot 304',
 'peugeot 504 sw': 'peugeot 504',
 'peugeot 604sl': 'peugeot 604',
 'peugeot 505s turbo diesel': 'peugeot 505',
 'plymouth fury iii': 'plymouth fury',
 'plymouth cricket': 'plymouth cricket',
 'plymouth satellite custom sw': 'plymouth satellite',
 'plymouth fury gran sedan': 'plymouth fury',
 'plymouth valiant': 'plymouth valiant',
 'plymouth duster': 'plymouth duster',
 'porsche macan': 'porsche macan',
 'porsche panamera': 'porsche panamera',
 'porsche cayenne': 'porsche cayenne',
 'porsche boxter': 'porsche boxster',
 'renault 12tl': 'renault 12',
 'renault 5 gtl': 'renault 5',
 'saab 99e': 'saab 99',
 'saab 99le': 'saab 99',
 'saab 99gle': 'saab 99',
 'subaru': 'subaru dl',
 'subaru dl': 'subaru dl',
 'subaru brz': 'subaru brz',
 'subaru baja': 'subaru baja',
 'subaru r1': 'subaru r1',
 'subaru r2': 'subaru r2',
 'subaru trezia': 'subaru trezia',
 'subaru tribeca': 'subaru tribeca',
 'toyota corona mark ii': 'toyota mark ii',
 'toyota corona': 'toyota corona',
 'toyota corolla 1200': 'toyota corolla',
 'toyota corona hardtop': 'toyota corona',
 'toyota corolla 1600 sw': 'toyota corolla',
 'toyota carina': 'toyota carina',
 'toyota mark ii': 'toyota mark ii',
 'toyota corolla': 'toyota corolla',
 'toyota corolla liftback': 'toyota corolla',
 'toyota celica gt liftback': 'toyota celica',
 'toyota corolla tercel': 'toyota tercel',
 'toyota corona liftback': 'toyota corona',
 'toyota starlet': 'toyota starlet',
 'toyota tercel': 'toyota tercel',
 'toyota cressida': 'toyota cressida',
 'toyota celica gt': 'toyota celica',
 'volkswagen rabbit': 'volkswagen golf',
 'volkswagen 1131 deluxe sedan': 'volkswagen beetle',
 'volkswagen model 111': 'volkswagen beetle',
 'volkswagen type 3': 'volkswagen type 3',
 'volkswagen 411 sw': 'volkswagen 411',
 'volkswagen super beetle': 'volkswagen beetle',
 'volkswagen dasher': 'volkswagen passat',
 'volkswagen rabbit custom': 'volkswagen golf',
 'volvo 145e sw': 'volvo 140 series',
 'volvo 144ea': 'volvo 140 series',
 'volvo 244dl': 'volvo 240 series',
 'volvo 245': 'volvo 240 series',
 'volvo 264gl': 'volvo 260 series',
 'volvo diesel': 'volvo 240 diesel',
 'volvo 246': 'volvo 240 series'}

In [42]:
all_model_corrections["audi 100ls"] = "audi 100 ls"

In [43]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa romeo giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa romeo stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa romeo Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100 ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0